name = "jamesc"
compatibility_date = "2023-07-24"
main = "workers-site/index.js"

kv_namespaces = [
    { binding = "KV", id = "9d382ae89e674bafa6d22391a64d3673", preview_id = "3ddce257ab694d0b965248e377a6bba1"}
]

[site]
bucket = "./dist"

[build]
command = "npm run build"